from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bench.benchmark_backends import BenchmarkCase, run_vllm_benchmark
from bench.collect_metrics import (
    collect_service_metrics,
    derive_service_delta,
    write_json,
)
from bench.config import load_settings


def update_single_case_manifest(
    *,
    batch_run_id: str,
    benchmark_dir: Path,
    case: BenchmarkCase,
) -> None:
    manifest_path = benchmark_dir / "manifest.json"
    existing: dict[str, Any] = {}
    if manifest_path.exists():
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))

    combined_files = sorted(benchmark_dir.glob("*.combined.json"))
    requested_suites = sorted(
        {
            *existing.get("requested_suites", []),
            case.suite,
        }
    )
    results = [
        {
            "case_id": path.name.removesuffix(".combined.json"),
            "combined_path": str(path),
        }
        for path in combined_files
    ]

    manifest = {
        "batch_run_id": batch_run_id,
        "matrix": existing.get("matrix"),
        "executed_at": datetime.now(timezone.utc).isoformat(),
        "requested_suites": requested_suites,
        "run_mode": "single_case",
        "planned_cases": max(int(existing.get("planned_cases", 0)), len(combined_files)),
        "completed_cases": len(combined_files),
        "failed_cases": int(existing.get("failed_cases", 0)),
        "results": results,
        "failures": existing.get("failures", []),
        "notes": existing.get(
            "notes",
            "Generated by bench/run_single_case.py for ad-hoc or smoke validation.",
        ),
        "cases": existing.get("cases", []),
    }

    manifest["cases"] = sorted(
        {
            *manifest["cases"],
            case.resolved_case_id(),
        }
    )
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def run_case(
    *,
    batch_run_id: str,
    case: BenchmarkCase,
    settings=None,
) -> dict[str, Any]:
    settings = settings or load_settings()
    benchmark_dir = settings.raw_benchmark_dir / batch_run_id
    prometheus_dir = settings.raw_prometheus_dir / batch_run_id
    benchmark_dir.mkdir(parents=True, exist_ok=True)
    prometheus_dir.mkdir(parents=True, exist_ok=True)

    case_id = case.resolved_case_id()
    before = collect_service_metrics(settings.vllm_base_url, settings.served_model_name)
    before_path = prometheus_dir / f"{case_id}.before.json"
    write_json(before_path, before)

    benchmark_execution = run_vllm_benchmark(
        settings=settings,
        case=case,
        result_dir=benchmark_dir,
        metadata={
            "suite": case.suite,
            "mode": case.mode,
            "case_id": case_id,
            "concurrency": str(case.concurrency),
            "input_tokens": str(case.input_tokens),
            "output_tokens": str(case.output_tokens),
            "repeat_index": str(case.repeat_index),
            "batch_run_id": batch_run_id,
        },
    )

    after = collect_service_metrics(settings.vllm_base_url, settings.served_model_name)
    after_path = prometheus_dir / f"{case_id}.after.json"
    write_json(after_path, after)

    service_delta = derive_service_delta(
        before,
        after,
        float(benchmark_execution["normalized_result"]["duration_s"]),
    )
    delta_path = prometheus_dir / f"{case_id}.delta.json"
    write_json(delta_path, service_delta)

    combined = {
        "batch_run_id": batch_run_id,
        "case_id": case_id,
        "executed_at": datetime.now(timezone.utc).isoformat(),
        "case": asdict(case),
        "benchmark_result_path": benchmark_execution["result_path"],
        "prometheus_before_path": str(before_path),
        "prometheus_after_path": str(after_path),
        "prometheus_delta_path": str(delta_path),
        "benchmark": benchmark_execution["normalized_result"],
        "service": service_delta,
    }
    combined_path = benchmark_dir / f"{case_id}.combined.json"
    write_json(combined_path, combined)
    update_single_case_manifest(
        batch_run_id=batch_run_id,
        benchmark_dir=benchmark_dir,
        case=case,
    )
    return combined


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a single Phase 2 benchmark case.")
    parser.add_argument("--batch-run-id", required=True)
    parser.add_argument("--suite", required=True)
    parser.add_argument("--mode", default="non_stream")
    parser.add_argument("--concurrency", type=int, required=True)
    parser.add_argument("--input-tokens", type=int, required=True)
    parser.add_argument("--output-tokens", type=int, required=True)
    parser.add_argument("--repeat-index", type=int, default=1)
    parser.add_argument("--num-prompts", type=int, default=None)
    parser.add_argument("--request-rate", type=float, default=None)
    parser.add_argument("--case-id", default=None)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    case = BenchmarkCase(
        suite=args.suite,
        mode=args.mode,
        concurrency=args.concurrency,
        input_tokens=args.input_tokens,
        output_tokens=args.output_tokens,
        repeat_index=args.repeat_index,
        num_prompts=args.num_prompts,
        request_rate=args.request_rate,
        case_id=args.case_id,
    )
    payload = run_case(batch_run_id=args.batch_run_id, case=case)
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
